### PR TITLE
[TorchToLinalg] Support `aten.full` fill value element type conversion

### LINKED ISSUE #4431: `aten.full` fails when fill value dtype differs from result dtype in TorchToLinalg
Currently, TorchToLinalg’s lowering of aten.full only handles trivial truncation and does not consistently convert fill scalars to the result element type. This causes mismatches or failed conversions when the fill value’s dtype differs from the result tensor’s dtype (e.g., int fill into bf16, float fill into i32).

### PR DESCRIPTION
**Pull request by janssen-v**
### Overview
The existing `aten.full` lowering in TorchToLinalg assumes the fill value’s dtype matches the result element type and only performed truncation in limited cases. This breaks cases like an int fill to a float tensor or vice versa, which we have encountered in a live production environment. The change in this PR preserves PyTorch semantics by converting fill scalars to the target element type with `convertScalarToDtype` and adds test coverage for mixed-dtype fills.

### Changes
- Fixes #4431 
- Add robust scalar dtype conversion for `aten.full` fill values via `convertScalarToDtype`.
- Add 4 tests covering fill value dtype conversions.
- Fix dynamic dim shape conversion issue.

### CODE REVIEW

**Comment by janssen-v** [comment]
Hi @zjgarvey, please review when free.

**Comment by zjgarvey** [comment]
Hi, do you have an example of this coming from a pytorch program or onnx etc? I'm not sure I understand why we would ever get an int fill value for a float tensor.

File: lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp [hunk 1]
```diff
@@ -208,33 +209,40 @@ class ConvertAtenFullOp : public OpConversionPattern<AtenFullOp> {
...
+        rewriter, loc, this->getTypeConverter(), inShape);
 
-      filteredShape.push_back(rewriter.getIndexAttr(resultTy.getDimSize(i)));
-    }
+    SmallVector<OpFoldResult> filteredShape = llvm::to_vector(llvm::map_range(
+        llvm::seq<int64_t>(resultTy.getRank()), [&](int64_t i) -> OpFoldResult {
+          if (resultTy.isDynamicDim(i))
+            return castIntToIndex(rewriter, loc, inShapeConverted[i]);
+          return rewriter.getIndexAttr(resultTy.getDimSize(i));
+        }));
```
Comment (zjgarvey) [inline lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: It's a bit difficult to parse exactly what is changing here.

1. why did this change from a loop?
2. how is this shape change related to the dtype support your PR is adding?

If it's just an efficiency thing you noticed as you were making a unrelated change, I would prefer that we put it into a separate PR.

**Comment by janssen-v** [comment]
> Hi, do you have an example of this coming from a pytorch program or onnx etc? I'm not sure I understand why we would ever get an int fill value for a float tensor.

Yeah, actually the original testcase from the first commit was cut out of a DeepSeek V3 graph running on MindSpeed. I will see if I still have the full graph from that case when I come into work tomorrow.

**EDIT**

This is the exact graph for which we wrote this fix for:
```
module {
  func.func @dsv3_1_forward_4.1(%arg0: !torch.vtensor<[2,8],si32>, %arg1: !torch.vtensor<[2048,2048],bf16>, %arg2: !torch.vtensor<[8,2048,7168],bf16>, %arg3: !torch.vtensor<[2,8],si32>, %arg4: !torch.vtensor<[2048],si64>) -> !torch.vtensor<[2048,7168],bf16> {
    %str = torch.constant.str "31"
    %int1 = torch.constant.int 1
    %int-1 = torch.constant.int -1
    %none = torch.constant.none
    %false = torch.constant.bool false
    %int15 = torch.constant.int 15
    %int0 = torch.constant.int 0
    %int2048 = torch.constant.int 2048
    %int7168 = torch.constant.int 7168
    %0 = torch.prim.ListConstruct %int2048, %int7168 : (!torch.int, !torch.int) -> !torch.list<int>
    %npu3A1 = torch.constant.device "npu:1"
    %1 = torch.aten.full %0, %int0, %int15, %int0, %npu3A1, %false : !torch.list<int>, !torch.int, !torch.int, !torch.int, !torch.Device, !torch.bool -> !torch.vtensor<[2048,7168],bf16>
    %2 = torch.prim.ListConstruct %int0 : (!torch.int) -> !torch.list<int>
    %3 = torch.aten.sum.dim_IntList %arg0, %2, %false, %none : !torch.vtensor<[2,8],si32>, !torch.list<int>, !torch.bool, !torch.none -> !torch.vtensor<[8],si64>
    %4 = torch.aten.cumsum %3, %int0, %none : !torch.vtensor<[8],si64>, !torch.int, !torch.none -> !torch.vtensor<[8],si64>
    %5 = torch.mindspeed.npu_gmm.Tensor %none, %arg1, %arg2, %none, %4, %int0, %false : !torch.none, !torch.vtensor<[2048,2048],bf16>, !torch.vtensor<[8,2048,7168],bf16>, !torch.none, !torch.vtensor<[8],si64>, !torch.int, !torch.bool -> !torch.vtensor<[2048,7168],bf16>
    %6 = torch.prim.ListConstruct %arg4 : (!torch.vtensor<[2048],si64>) -> !torch.list<optional<vtensor>>
    %7 = torch.aten.index_put %1, %6, %5, %false : !torch.vtensor<[2048,7168],bf16>, !torch.list<optional<vtensor>>, !torch.vtensor<[2048,7168],bf16>, !torch.bool -> !torch.vtensor<[2048,7168],bf16>
    %8 = torch.prim.ListConstruct %int-1, %int1, %int7168 : (!torch.int, !torch.int, !torch.int) -> !torch.list<int>
    %9 = torch.aten.reshape %7, %8 : !torch.vtensor<[2048,7168],bf16>, !torch.list<int> -> !torch.vtensor<[2048,1,7168],si32>
    %10 = torch.prim.ListConstruct %int1 : (!torch.int) -> !torch.list<int>
    %11 = torch.aten.sum.dim_IntList %9, %10, %false, %none : !torch.vtensor<[2048,1,7168],si32>, !torch.list<int>, !torch.bool, !torch.none -> !torch.vtensor<[2048,7168],bf16>
    %12 = torch.prim.ListConstruct %int-1 : (!torch.int) -> !torch.list<int>
    %13 = torch.aten.sum.dim_IntList %arg0, %12, %false, %none : !torch.vtensor<[2,8],si32>, !torch.list<int>, !torch.bool, !torch.none -> !torch.vtensor<[2],si64>
    %14 = torch.prim.ListConstruct %int1 : (!torch.int) -> !torch.list<int>
    %15 = torch.aten.sum.dim_IntList %arg3, %14, %false, %none : !torch.vtensor<[2,8],si32>, !torch.list<int>, !torch.bool, !torch.none -> !torch.vtensor<[2],si64>
    %16 = torch.mind.all_to_all_v %11, %int2048, %13, %15, %str : !torch.vtensor<[2048,7168],bf16>, !torch.int, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>, !torch.str -> !torch.vtensor<[2048,7168],bf16>
    return %16 : !torch.vtensor<[2048,7168],bf16>
  }
}
```
```
full_default: "bf16[2048, 7168]" = torch.ops.aten.full.default([2048, 7168], 0, dtype = torch.bfloat16, layout = torch.strided, device = device(type='npu', index=1), pin_memory = False)
```
I checked the FXGraph dumps and it seems that in this specific case, the full op's `0` fill value literal gets exported into the torch dialect as a integer constant. We eventually sidestepped this issue by adding a decomposition rule for the full op in Inductor, but it would be nice for the case to have been supported natively.

File: lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp [hunk 2]
```diff
@@ -208,33 +209,40 @@ class ConvertAtenFullOp : public OpConversionPattern<AtenFullOp> {
...
+    if (auto originalTensorTy =
+            dyn_cast<RankedTensorType>(op.getResult().getType())) {
+      dstOriginalDtype = originalTensorTy.getElementType();
+    }
+
+    Value castedFull = convertScalarToDtype(
+        rewriter, loc, full, targetElementType, srcOriginalDtype,
+        dstOriginalDtype, op.getFillValue());
+
+    if (!castedFull) {
```
Comment (zjgarvey) [inline lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: This condition won't get reached (an error would get thrown before that function returns a `nullptr`).

If this function was intended to be further validated after calling, it would be better to make it a `FailureOr<Value>` so we can better catch failures during the conversion.

File: lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp [hunk 3]
```diff
@@ -208,33 +209,40 @@ class ConvertAtenFullOp : public OpConversionPattern<AtenFullOp> {
...
-      if (isa<mlir::FloatType>(full.getType())) {
-        full = arith::TruncFOp::create(rewriter, loc, resultTy.getElementType(),
-                                       full);
-      } else if (isa<mlir::IntegerType>(full.getType())) {
-        full = arith::TruncIOp::create(rewriter, loc, resultTy.getElementType(),
-                                       full);
-      }
+    if (auto originalTensorTy =
+            dyn_cast<RankedTensorType>(op.getResult().getType())) {
+      dstOriginalDtype = originalTensorTy.getElementType();
```
Comment (zjgarvey) [inline lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: 1. This check won't succeed because the result of the torch op is a `torch::ValueTensorType` and not a builtin type.

2. I think the purpose of `dstOriginalDtype` was supposed to be the dtype coming from the original `ValueTensorType`.

File: lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp (hunk 1 above)
Comment (janssen-v) [reply lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: 1. Yeah it's just an efficiency thing. In our internal codebase we try to avoid using loops when the logic can be expressed clearly with `to_vector` mainly to let LLVM handle size reservation automatically. Since it's not critical to the main purpose of this PR, I'll revert it here and perhaps submit it for a NFC cleanup PR later.

2. I found that the simplified test cases with dynamic shape tensors wouldn't pass otherwise as `inShape[i]` that is pushed back to `filteredShape` would be an int value instead of an index value, which causes a failure in the creation of the `tensor::emptyOp outTensor`. For non-dynamic dim cases in the original loop, the logic wraps the dim size with a rewriter to convert it to an index value, so I am inclined to believe that this is a bug.
```
// Original handling for when dim(i) is not dynamic
filteredShape.push_back(rewriter.getIndexAttr(resultTy.getDimSize(i)));
```

File: lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp (hunk 3 above)
Comment (janssen-v) [reply lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: Oh yeah, missed that. Fixed in [1e790a4e](https://github.com/llvm/torch-mlir/pull/4432/commits/1e790a4eb79afc81364904c3abb07be0279e2d48)

File: lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp (hunk 2 above)
Comment (janssen-v) [reply lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: Fixed in [a830830b](https://github.com/llvm/torch-mlir/pull/4432/commits/a830830b11f43ba224cfcf31b5547f3046b9d6c1)

Comment (zjgarvey) [reply lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: This condition still wouldn't get reached since you are casting a `Value` to a `FailureOr<Value>`. My point was that currently the compiler program will exit with an error if the helper function fails. The match failure and condition will never get reached, so you should remove them.

We could, in a separate patch, consider changing the helper function to return a failure instead of throwing an error, but that would be a pretty major change.

File: lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp (hunk 1 above)
Comment (zjgarvey) [reply lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: Ah, nice catch!

Sounds good to me.

File: lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp (hunk 2 above)
Comment (janssen-v) [reply lib/Conversion/TorchToLinalg/TensorScalarInterop.cpp]: Oh, oops. I misunderstood what you meant. But yeah, I agree that the best solution is for the helper to be refactored to return a `FailureOr<Value>` eventually. I might pick it up if I have some downtime in the future.

In the meantime, I've removed the check for the match failure and squashed the commits down to the 2 relevant changes made by this PR.

**Comment by janssen-v** [comment]
Hey @zjgarvey , mind taking a look again? I've removed the conditional check to address your previous review.
